force-app/main/default/objects/Case_history__c/Case_history__c.object-meta.xml
<CustomObject>
    <label>Case History</label>
    <nameField>
        <label>Case history Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_history__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Histories</relationshipLabel>
    <relationshipName>Case_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_history__c/fields/Old_value_of_Priority__c.field-meta.xml
<CustomField>
    <fullName>Old_value_of_Priority__c</fullName>
    <label>Old value of Priority</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaseHistoryHandler.cls
public class CaseHistoryHandler {
    
    public void handleAfterUpdate(List<Case> oldCases, List<Case> newCases) {
        checkCaseStatus(oldCases, newCases);
    }
    
    private static void checkCaseStatus(List<Case> oldCases, List<Case> newCases) {
        List<Case_History__c> histories = new List<Case_History__c>();
        for(Integer i = 0 ; i < newCases.size() ; i++ ) {
            if(newCases[i].id == oldCases[i].id && newCases[i].priority != oldCases[i].priority) {
                histories.add(new Case_History__c(Case__c = oldCases[i].id, Case_Number__c = oldCases[i].CaseNumber, Old_value_of_Priority__c = oldCases[i].priority));
            }
        }
        
        try {
            INSERT histories;
        }catch(Exception e) {
            System.debug(e.getMessage());
        }
    } 
}