force-app/main/default/objects/Account/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/age__c.field-meta.xml
<CustomField>
    <fullName>age__c</fullName>
    <label>age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Exp__c.field-meta.xml
<CustomField>
    <fullName>Exp__c</fullName>
    <label>Exp</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>selected</fullName>
            </value>
            <value>
                <fullName>Not selected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactTriggerHandler.cls
public class ContactTriggerHandler {
    public static void userCreation(List<Contact> newContactList){
        for(contact con: newContactList){
            if(con.age__c < 30 && con.Exp__c > 8){
                con.status__c = 'selected';
            }
        }
        
    }
    
   
    /*
public static void selectiveContactCreation(List<Contact> newContactList){
for(contact con: newContactList) {
List<account> acc = [SELECT id,(SELECT id FROM contacts) FROM account where ID = :con.AccountId];
system.debug(acc[0].contacts);
if(acc[0].contacts.size() >= 10){
con.addError('you cant add more then 10 records');
}
}
}*/
}