force-app/main/default/objects/attendence_details__c/attendence_details__c.object-meta.xml
<CustomObject>
    <label>attendence detail</label>
    <nameField>
        <label>student name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>attendence details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/attendence_details__c/fields/dec__c.field-meta.xml
<CustomField>
    <fullName>dec__c</fullName>
    <label>dec</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/attendence_details__c/fields/feb__c.field-meta.xml
<CustomField>
    <fullName>feb__c</fullName>
    <label>feb</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/attendence_details__c/fields/jan__c.field-meta.xml
<CustomField>
    <fullName>jan__c</fullName>
    <label>jan</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/svnp_school__c/svnp_school__c.object-meta.xml
<CustomObject>
    <label>svnp school</label>
    <nameField>
        <label>student name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>svnp schools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/svnpattendencehandler.cls
public class svnpattendencehandler {
    public static void studentattendence(list<svnp_school__c>studentlist){
        list<attendence_details__c>listofattendence = new list<attendence_details__c>();
        for(svnp_school__c studentdet :studentlist){
           attendence_details__c att = new attendence_details__c();
           att.Name = studentdet.Name;
            att.jan__c = 0;
            att.feb__c = 0;
            att.dec__c = '0';
            
            //insert operation
            listofattendence.add(att);
            insert listofattendence;
        }
    }
}