force-app/main/default/objects/Mobile__c/Mobile__c.object-meta.xml
<CustomObject>
    <label>Mobile</label>
    <nameField>
        <label>customer name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mobiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mobile__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Samsung</fullName>
            </value>
            <value>
                <fullName>Apple</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mobile__c/fields/Discount_status__c.field-meta.xml
<CustomField>
    <fullName>Discount_status__c</fullName>
    <label>Discount status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/mobiletriggerhandler.cls
public class mobiletriggerhandler{
    public static void mobilediscount(List<Mobile__c> newdiscountList1){
        for(Mobile__c dis: newdiscountlist1){
            if(dis.Brand__c == 'samsung'){
            dis.Price__c=dis.Price__c - (dis.Price__c*10)/100;
                dis.Discount_status__c='you have got 10% discount';
            }
            else if(dis.Brand__c== 'Apple'){
                dis.Price__c=dis.Price__c -(dis.Price__c*20)/100;
                dis.Discount_status__c='you have got 20% discount';
            }
        }
        
    }
}